name: dstore_middleware_dio
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=3.10.0 <4.0.0"
resolution: workspace
dependencies:
  dstore:
    path: ../dstore
  dio: ^4.0.0
dev_dependencies:
  pedantic:
