name: dstore_mono1
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=3.6.0 <4.0.0"
publish_to: none
workspace:

dev_dependencies:
  pedantic:
  melos: ^7.3.0

melos:
  name: dstore_mono1
  packages:
    - packages/*
