name: dstore_storage_sharedprefs
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=3.10.0 <4.0.0"
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  dstore:
    path: ../dstore
  shared_preferences: 2.1.0

dev_dependencies:
  test:
  grinder:
