name: network_status_default
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=3.10.0 <4.0.0"
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  meta:
  connectivity: 3.0.0-nullsafety.3
  dstore:
    path: ../dstore

dev_dependencies:
  pedantic:
